"""Email delivery.

Sends an HTML digest with the top matches inline (so the report is useful
from the notification alone) plus the full PDF as an attachment.
"""

from __future__ import annotations

import html
import logging
import smtplib
from datetime import date
from email.message import EmailMessage
from pathlib import Path

from sources.base import Job

log = logging.getLogger(__name__)


def _rows(jobs: list[Job]) -> str:
    out = []
    labels = {
        "fresher": ("FRESHER OK", "#1e6f4a"),
        "fits": ("IN RANGE", "#1a4f8a"),
        "stretch": ("STRETCH", "#9a6b1a"),
        "unclear": ("NOT STATED", "#9a9a9a"),
    }
    for j in jobs:
        age = "today" if (j.days_old or 0) <= 0 else f"{j.days_old}d ago"
        blabel, bcolour = labels.get(j.eligibility, labels["unclear"])
        if j.eligibility == "stretch" and j.years_required:
            blabel = f"ASKS {j.years_required}y"
        out.append(
            "<tr>"
            f'<td style="padding:8px 10px;border-bottom:1px solid #e6e6e6;'
            f'font:600 15px/1.2 -apple-system,Segoe UI,sans-serif;'
            f'color:#1e6f4a;text-align:center">{j.score:.0f}'
            f'<div style="font:600 8px/1.4 -apple-system,sans-serif;'
            f'color:{bcolour};letter-spacing:.3px">{blabel}</div></td>'
            f'<td style="padding:8px 10px;border-bottom:1px solid #e6e6e6;'
            f'font:14px/1.4 -apple-system,Segoe UI,sans-serif">'
            f'<a href="{html.escape(j.url, quote=True)}" '
            f'style="color:#1a4f8a;text-decoration:none;font-weight:600">'
            f'{html.escape(j.title)}</a><br>'
            f'<span style="color:#6b6b6b;font-size:12px">'
            f'{html.escape(j.company)} &middot; {html.escape(j.location)} '
            f'&middot; {age}</span></td>'
            "</tr>"
        )
    return "".join(out)


def _build_html(by_track: dict[str, list[Job]], track_labels: dict[str, str],
                inline_top_n: int, run_meta: dict) -> str:
    sections = []
    for track, jobs in by_track.items():
        label = html.escape(track_labels.get(track, track))
        if not jobs:
            sections.append(
                f'<h3 style="font:600 15px -apple-system,Segoe UI,sans-serif;'
                f'color:#1a1a1a;margin:22px 0 6px">{label}</h3>'
                f'<p style="font:italic 13px -apple-system,sans-serif;'
                f'color:#6b6b6b;margin:0">Nothing new today.</p>'
            )
            continue
        more = len(jobs) - inline_top_n
        tail = (f'<p style="font:12px -apple-system,sans-serif;color:#6b6b6b;'
                f'margin:8px 0 0">+ {more} more in the attached PDF.</p>'
                if more > 0 else "")
        sections.append(
            f'<h3 style="font:600 15px -apple-system,Segoe UI,sans-serif;'
            f'color:#1a1a1a;margin:22px 0 6px">{label} '
            f'<span style="color:#6b6b6b;font-weight:400">({len(jobs)})</span></h3>'
            f'<table cellpadding="0" cellspacing="0" width="100%" '
            f'style="border-collapse:collapse">{_rows(jobs[:inline_top_n])}</table>'
            f'{tail}'
        )

    return (
        '<div style="max-width:640px;margin:0 auto;padding:8px">'
        '<h2 style="font:700 20px -apple-system,Segoe UI,sans-serif;'
        'color:#1a1a1a;margin:0 0 2px">Daily Job Report</h2>'
        f'<p style="font:13px -apple-system,sans-serif;color:#6b6b6b;margin:0">'
        f'{date.today().strftime("%A, %d %B %Y")} &middot; '
        f'{run_meta["new_count"]} new &middot; '
        f'posted within {run_meta["max_days_old"]} days</p>'
        + "".join(sections) +
        '<p style="font:11px -apple-system,sans-serif;color:#9a9a9a;'
        'margin:26px 0 0;border-top:1px solid #e6e6e6;padding-top:10px">'
        'Generated by your job agent. Scores blend resume skill overlap, title '
        'relevance, freshness and seniority fit. Postings already sent in an '
        'earlier report are suppressed.</p></div>'
    )


def send_email(
    *,
    smtp_host: str,
    smtp_port: int,
    username: str,
    password: str,
    to_addr: str,
    subject: str,
    by_track: dict[str, list[Job]],
    track_labels: dict[str, str],
    inline_top_n: int,
    run_meta: dict,
    attachment: Path | None = None,
) -> None:
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = username
    msg["To"] = to_addr

    plain_lines = [f"Daily Job Report — {date.today().isoformat()}", ""]
    for track, jobs in by_track.items():
        plain_lines.append(track_labels.get(track, track))
        if not jobs:
            plain_lines.append("  (nothing new)")
        for j in jobs:
            plain_lines.append(f"  [{j.score:.0f}] {j.title} — {j.company} "
                               f"({j.location})\n      {j.url}")
        plain_lines.append("")
    msg.set_content("\n".join(plain_lines))
    msg.add_alternative(
        _build_html(by_track, track_labels, inline_top_n, run_meta),
        subtype="html",
    )

    if attachment and attachment.exists():
        msg.add_attachment(
            attachment.read_bytes(),
            maintype="application",
            subtype="pdf",
            filename=attachment.name,
        )

    with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as s:
        s.starttls()
        s.login(username, password)
        s.send_message(msg)
    log.info("email sent to %s", to_addr)
